# Generated by Django 5.0.7 on 2024-07-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_completo', models.CharField(max_length=100)),
                ('profissao', models.CharField(choices=[('MEDICO', 'Médico'), ('PSICOLOGO', 'Psicólogo'), ('OUTRO', 'Outro')], max_length=20)),
                ('endereco', models.TextField()),
                ('celular', models.CharField(max_length=11)),
                ('nome_social', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('especialidade_medica', models.CharField(choices=[('CARDIOLOGIA', 'Cardiologia'), ('DERMATOLOGIA', 'Dermatologia'), ('GINECOLOGIA', 'Ginecologia'), ('PEDIATRIA', 'Pediatria'), ('PSIQUIATRIA', 'Psiquiatria'), ('PSICOLOGIA', 'Psicologia'), ('OUTRO', 'Outro')], max_length=20)),
                ('foto_documento', models.ImageField(upload_to='fotos_documentos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pessoa Profissional',
                'verbose_name_plural': 'Pessoas Profissionais',
                'indexes': [models.Index(fields=['email'], name='contas_pess_email_708032_idx'), models.Index(fields=['cpf'], name='contas_pess_cpf_3e0098_idx')],
            },
        ),
    ]
