# Generated by Django 5.0.7 on 2024-07-19 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social_medico', models.CharField(max_length=100)),
                ('especialidade_medica', models.CharField(choices=[('CARDIOLOGIA', 'Cardiologia'), ('DERMATOLOGIA', 'Dermatologia'), ('GINECOLOGIA', 'Ginecologia'), ('PEDIATRIA', 'Pediatria'), ('PSIQUIATRIA', 'Psiquiatria'), ('PSICOLOGIA', 'Psicologia'), ('OUTRO', 'Outro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('pessoa_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
