# Generated by Django 5.0.7 on 2024-07-19 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_remove_consulta_data_remove_consulta_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
