# Generated by Django 5.0.7 on 2024-07-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_consulta_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='nome_social_medico',
            new_name='medico',
        ),
    ]
